---
- hosts: web
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Copy application jar to EC2
      copy:
        src: target/spring-petclinic-3.3.0-SNAPSHOT.jar
        dest: /home/ubuntu/spring-petclinic-3.3.0-SNAPSHOT.jar

    - name: Copy systemd service file
      copy:
        content: |
          [Unit]
          Description=Spring Boot Application
          After=network.target

          [Service]
          User=ubuntu
          ExecStart=java -jar /home/ubuntu/spring-petclinic-3.3.0-SNAPSHOT.jar
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/spring-petclinic.service

    - name: Start and enable the service
      systemd:
        name: spring-petclinic
        enabled: yes
        state: restarted